dist: trusty
sudo: required
language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends libfuse-dev libsqlite3-dev libavcodec-dev libavformat-dev libavresample-dev libavutil-dev libswscale-dev asciidoc xmlto
script: ./autogen.sh && ./configure && make
